services:
  - type: web
    name: stem-quest-backend
    env: node
    rootDir: "STEM QUEST/server"
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
      - key: MONGODB_URI
        sync: false # You will need to paste your MongoDB Atlas URL in Render dashboard
      - key: JWT_SECRET
        generateValue: true
