services:
  - type: web
    name: stem-quest-backend
    env: node
    rootDir: "STEM QUEST/server"
    buildCommand: "npm install"
    startCommand: "node index.js"
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
      - key: MONGODB_URI
        sync: false # Paste your MongoDB Atlas string here
      - key: JWT_SECRET
        generateValue: true
