services:
  - type: web
    name: stem-quest-backend
    env: node
    buildCommand: 'cd "STEM QUEST/server" && npm install'
    startCommand: 'cd "STEM QUEST/server" && node index.js'
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
      - key: MONGODB_URI
        sync: false # Paste your MongoDB Atlas string here
      - key: JWT_SECRET
        generateValue: true
